version: '3.7'
services:
  mongo:
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "'db.adminCommand(\"ping\")'"
        ]
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - 6379:6379
      # - private
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "redis", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5

networks:
  default:
    driver: bridge
