version: '3.7'
services:
  mongo:
    image: mongo:6.0
    command:
      - bash
      - "-c"
      - |
        echo 'Initializing replica set in the background...'
        (sleep 10; mongosh --eval "try { rs.conf(); } catch (e) { rs.initiate({_id : 'rs0', members: [{ _id: 0, host: 'localhost:27017' }]}); }")&
        echo 'Running mongod in the foreground...'
        exec mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./docker-containers/mongo:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "'db.adminCommand(\"ping\")'"
        ]
      interval: 5s
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    volumes:
      - ./docker-containers/redis:/data
    ports:
      - 6379:6379
      # - private
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "redis", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 10

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./docker-containers/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 15s
      retries: 5

networks:
  default:
    driver: bridge
