version: '3.7'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    logging:
      options:
        max-size: 10m
        max-file: '3'
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  events-fetcher:
    image: events-fetcher
    build:
      context: ./
      dockerfile: apps/events-fetcher/Dockerfile
    restart: always
    ports:
      - 3001:3001
